---
- hosts: webserver
  remote_user: ec2-user
  become: yes
  become_method: sudo

  roles:
    - ansible-role-firewalld
  vars:
    firewalld_state: latest
    firewall_debug: true
    firewalld_rules:
      ssh:
        port: 22
        protocol: tcp
        state: enabled
        zone: public
        permanent: true
      http:
        port: 80
        protocol: tcp
        state: enabled
        zone: public
        permanent: true
      https:
        port: 443
        protocol: tcp
        state: enabled
        zone: public
        permanent: true
